stages:
  - docs
  - deploy

variables:
  DOCS_IMAGE_NAME: "quarto-templates-docs-prod"
  DOCS_CONTAINER_NAME: "quarto-templates-docs-prod"
  DOCS_PORT: 31270


docs-vm-local:
  stage: docs
  script:
    - docker image build . -t "${DOCS_IMAGE_NAME}" -f ".docker/docs.dockerfile"
    - |
      # Stop and remove the container if it is running
      if [ $(docker container ls -q -f name="${DOCS_CONTAINER_NAME}") ]; then
          docker container stop ${DOCS_CONTAINER_NAME}
          docker container rm ${DOCS_CONTAINER_NAME}
      fi
    - docker container run -d -p ${DOCS_PORT}:5000 --name "${DOCS_CONTAINER_NAME}" ${DOCS_IMAGE_NAME} quarto preview . --host 0.0.0.0 --port 5000 --render all
  only:
    - master
  tags:
    - shell


deploy-github:
  image:
    name: alpine/git:2.40.1
    entrypoint: [""]
  stage: deploy
  script:
    - echo 'echo $GITHUB_ACCESS_TOKEN' > $HOME/.git_askpass.sh
    - chmod +x $HOME/.git_askpass.sh
    - export GIT_ASKPASS=$HOME/.git_askpass.sh

    - git remote set-url github https://git@github.com/profinit/quarto-templates.git
    - git fetch --all
    - git checkout master || git checkout -b master
    - git push github --force
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
      when: manual
    - if: '$CI_COMMIT_REF_NAME == "master" && $CI_COMMIT_TAG'
  tags:
    - quarto-templates
