stages:
  - deploy

deploy:
  tags:
    - quarto-templates
  image:
    name: alpine/git:2.40.1
    entrypoint: [""]
  stage: deploy
  script:
    - git config --global url."https://api@github.com/".insteadOf "https://github.com/"
    - git config --global url."https://ssh@github.com/".insteadOf "ssh://git@github.com/"
    - git config --global url."https://git@github.com/".insteadOf "git@github.com:"
    - echo 'echo $GITHUB_ACCESS_TOKEN' > $HOME/.git_askpass.sh
    - chmod +x $HOME/.git_askpass.sh
    - export GIT_ASKPASS=$HOME/.git_askpass.sh

    - git remote set-url github git@github.com:profinit/quarto-templates.git
    - git fetch --all
    - git checkout master || git checkout -b master
    - git push github --force
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
