---
title: "Project Installation"
format:
    profinit-html:
        number-sections: true
---

In this document, we describe how to install this project from a developer's perspective. Thus, we will install all dependencies and programs necessary for development.

## Cloning the Project

::: {.panel-tabset}

## Linux (http)

```sh
git clone https://git.profinit.eu/DataScience/Sablony/quarto-templates
```

## Linux (ssh)

```sh
git clone git@git.profinit.eu:datascience/sablony/quarto-templates.git
```

## Windows (http)

```sh
git clone -c core.symlinks=true https://git.profinit.eu/datascience/sablony/quarto-templates.git
```

## Windows (ssh)

```sh
git clone -c core.symlinks=true git@git.profinit.eu:datascience/sablony/quarto-templates.git
```

:::

## Installing Quarto

Quarto installation is described in the [Quarto Documentation](https://quarto.org/).

## Installing Python

To run Quarto documents with code cells written in Python, it's necessary to install Python. Suitable installation scripts can be found [here](https://www.python.org/downloads/). We recommend Python version at least 3.10, but it will probably work with lower versions as well.

Then we create and activate a virtual environment using the following commands:

::: {.panel-tabset}

### Linux

```{.sh}
python -m venv "venv"
source venv/bin/activate
python -m pip install -r "requirements.txt"
```

### Windows (Powershell)

```{.powershell}
python -m venv "venv"
./venv/Scripts/Activate.ps1
python -m pip install -r "requirements.txt"
```

:::

## Installing R

TODO

## Checking the Installation

After installing all necessary components, we recommend running the following command to check that the installation went well:

```{.sh}
quarto check
```

This command should return approximately the following output:

```
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.1.1: OK
      Dart Sass version 1.55.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.3.433
      Path: /opt/quarto/1.3.433/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.10.10
      Path: /home/username/quarto-templates/venv/bin/python3
      Jupyter: 5.3.0
      Kernels: python3, jmeno_kernelu

[✓] Checking Jupyter engine render....OK

[✓] Checking R installation...........OK
      Version: 4.3.0
      Path: /usr/lib64/R
      LibPaths:
        - /usr/lib64/R/library
        - /usr/share/R/library
      knitr: 1.42
      rmarkdown: 2.20

[✓] Checking Knitr engine render......OK
```

If any part failed, it is necessary to fix its installation.
