project:
  type: website
  execute-dir: project

website:
  title: "Quarto templates"
  favicon: favicon.png
  repo-url: https://git.profinit.eu/datascience/sablony/quarto-templates
  repo-branch: master
  repo-subdir: docs
  repo-actions: [edit, issue]
  sidebar: 
    style: docked
    contents: 
      - quick_start.qmd
      - dev_guide.qmd
      - faqs.qmd
      - section: examples/examples.qmd
        contents: 
        - examples/template.qmd
        - examples/template_py.qmd
        - examples/template_r.qmd
    background: "#bd3632"
    foreground: "#ffffff"
    
  
format:
  profinit-html:
    toc: true
    title-block-banner: false
    lang: cs
