project:
  type: website

website:
  title: "Quarto Templates"
  favicon: favicon.png
  repo-url: https://git.profinit.eu/datascience/sablony/quarto-templates
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit]
  back-to-top-navigation: true
  page-navigation: true

  navbar:
    search: true
    tools:
      - icon: git
        url: https://git.profinit.eu/datascience/sablony/quarto-templates
    left:
      - text: For Users
        menu:
          - text: Quick Start
            href: users/quickstart.qmd
          - text: Examples
            href: users/examples/index.qmd
          - text: Tips and Tricks
            href: users/tricks/index.qmd
      - text: For Developers
        menu:
        - developers/install.qmd
        - developers/run.qmd
        - developers/release.qmd

  sidebar: 
    - id: users
      title: For Users
      style: docked
      contents: 
        - users/quickstart.qmd
        - section: users/examples/index.qmd
          contents: 
            - text: No Code
              file: users/examples/example.qmd
            - text: Python
              file: users/examples/example_py.qmd
            - text: R
              file: users/examples/example_r.qmd
        - section: users/tricks/index.qmd
          contents:
            - text: General
              file: users/tricks/general.qmd
            - text: Python
              file: users/tricks/python.qmd
            - text: R
              file: users/tricks/r.qmd

    - id: developers
      title: For Developers
      style: docked
      contents:
        - developers/install.qmd
        - developers/run.qmd
        - developers/release.qmd

  
format:
  profinit-html:
    toc: true
    title-block-banner: false
    lang: en
    css: style.css
    smooth-scroll: true
