project:
  type: website

website:
  title: "Quarto Templates"
  favicon: favicon.png
  repo-url: https://git.profinit.eu/datascience/sablony/quarto-templates
  repo-branch: main
  repo-subdir: docs
  repo-actions: [edit]

  navbar:
    search: true
    tools:
      - icon: git
        url: https://git.profinit.eu/datascience/sablony/quarto-templates
    left:
      - sidebar:users
      - sidebar:developers
  sidebar: 
    - id: users
      title: Pro uživatele
      style: docked
      contents: 
        - users/quickstart.qmd
        - users/tricks.qmd
        - section: users/examples/index.qmd
          contents: 
            - text: Bez kódu
              file: users/examples/example.qmd
            - text: Python
              file: users/examples/example_py.qmd
            - text: Python (Jupyter)
              file: users/examples/example_py_jupyter.ipynb
            - text: R
              file: users/examples/example_r.qmd
    - id: developers
      title: Pro vývojáře
      style: docked
      contents:
        - developers/install.qmd
        - developers/run.qmd
        - developers/release.qmd
    
  
format:
  profinit-html:
    toc: true
    title-block-banner: false
    lang: cs
